[package]
name = "outliner-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
outliner-core = { path = "../core" }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
regex = "1.10"
chrono = { version = "0.4", features = ["clock", "std"] }

