[package]
name = "outliner-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "outliner"
path = "src/main.rs"

[dependencies]
outliner-core = { path = "../core" }
outliner-tui = { path = "../tui" }
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }

